# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
# Please note that the CD section (from Line 24 onwards) is sourced from https://medium.com/swlh/set-up-ci-cd-with-azure-and-github-under-10-minutes-39a6846fff90

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git checkout $(Build.SourceBranchName)
      git remote add heroku https://heroku:$(heroku-token)@git.heroku.com/risk-management-platform.git
      git push heroku $(Build.SourceBranchName)